### PR TITLE
Feature/add space navbar

### PR DESCRIPTION
**Pull request by Findsay**
Adds a nav bar with the planet icons, can't get it to not show on homescreen though but is fixed in place when scrolling. Could probably refactor to autogenerate if we want?

### CODE REVIEW

**Comment by Findsay** [comment]
screen shot 2017-12-16 at 19 51 33

**Comment by hdpuk86** [comment]
I don't mind it being on the home screen. Makes it easy to use from the start.

**Comment by JamieSK** [comment]
I also don't mind it being on the homescreen, though it's slightly less minimal. Something to decide probably, I think the best way to do it would be bringing the planets div in front of it and fill it with black so it would slide out from underneath as you scroll.

**Review by JamieSK — APPROVED** [review]
I like it

**Pull request merged**
