### PR TITLE
Feature/add hover event listener for each planet

### PR DESCRIPTION
**Pull request by hdpuk86**
I added a hidden div to each planet in the homeview that contains a ul of their basic stats. The event listener just makes it visible on hover. The circles now glow and I lined them up but didn't space them yet. The ticket said to write the event listener in the app.js but I can move it into the homeView and it works if we wanted to keep the app.js clean and use the one request? I don't know which is better.

### CODE REVIEW

**Comment by Findsay** [comment]
Looks great, i think maybe move the creation of the event listener to the planetView? I think that would keep it consistent, that way the planetView returns the planet div with the circle div and hidden hover div. So require the hoverview in planetView, homeView still just calls planetView and the app just makes the request.

**Review by JamieSK — CHANGES_REQUESTED** [review]
I think what Fiona says but it looks great once it's moved into planetView

**Comment by hdpuk86** [comment]
I tried moving it to planetView but it doesn't like adding a listener to an element at the same time as creating the element. So I moved it back to homeView and its working. Is that ok?

**Review by JamieSK — APPROVED** [review]
Tidy

**Review by Findsay — APPROVED** [review]

**Pull request merged**
